USE DATABASE FLIGHTS;
USE SCHEMA PUBLIC;


CREATE OR REPLACE TABLE TRAVEL_CLEAN AS
SELECT DISTINCT
    TRIM(TRANSACTION_KEY) AS transaction_key,
    TRIM(TICKETING_AIRLINE) AS ticketing_airline,
    TRIM(AGENCY) AS agency,
    TRY_TO_DATE(ISSUE_DATE) AS issue_date
FROM TRAVEL_RAW
WHERE TRANSACTION_KEY IS NOT NULL;


CREATE OR REPLACE TABLE TRAVEL_GOLD AS
SELECT
    ticketing_airline,
    COUNT(*) AS total_transactions
FROM TRAVEL_CLEAN
WHERE ticketing_airline IS NOT NULL
GROUP BY ticketing_airline;