CREATE OR REPLACE TABLE FLIGHTS.SILVER.DIM_AIRLINE (
AIRLINE_ID INTEGER AUTOINCREMENT,
TICKETING_AIRLINE STRING,
MARKETING_AIRLINE STRING,
PRIMARY KEY (AIRLINE_ID)
);

CREATE OR REPLACE TABLE FLIGHTS.SILVER.DIM_ROUTE (
ROUTE_ID INTEGER AUTOINCREMENT,
ORIGIN STRING,
DESTINATION STRING,
COUNTRY STRING,
PRIMARY KEY (ROUTE_ID)
);

CREATE OR REPLACE TABLE FLIGHTS.SILVER.FACT_TRAVEL (
EVENT_ID STRING DEFAULT UUID_STRING(),
TRANSACTION_KEY STRING,
AIRLINE_ID INTEGER,
ROUTE_ID INTEGER,
CABIN STRING,
AGENCY STRING,
DEPARTURE_DATE DATE,
ISSUE_DATE DATE,
FLIGHT_NUMBER STRING,
SEG_NUMBER STRING
);