INSERT INTO FLIGHTS.SILVER.DIM_AIRLINE
SELECT DISTINCT
TICKETING_AIRLINE,
MARKETING_AIRLINE
FROM FLIGHTS.BRONZE.TRAVEL_RAW
WHERE TICKETING_AIRLINE IS NOT NULL;

INSERT INTO FLIGHTS.SILVER.DIM_ROUTE
SELECT DISTINCT
ORIGIN,
DESTINATION,
COUNTRY
FROM FLIGHTS.BRONZE.TRAVEL_RAW;

INSERT INTO FLIGHTS.SILVER.FACT_TRAVEL
SELECT
UUID_STRING(),
TRANSACTION_KEY,
NULL,
NULL,
CABIN,
AGENCY,
TRY_TO_DATE(DEPARTURE_DATE),
TRY_TO_DATE(ISSUE_DATE),
FLIGHT_NUMBER,
SEG_NUMBER
FROM FLIGHTS.BRONZE.TRAVEL_RAW;