INSERT INTO FLIGHTS.SILVER.AIRLINE
(
TICKETING_AIRLINE,
MARKETING_AIRLINE
)
SELECT DISTINCT
TRIM(TICKETING_AIRLINE),
TRIM(MARKETING_AIRLINE)
FROM FLIGHTS.BRONZE.TRAVEL_RAW
WHERE TRANSACTION_KEY IS NOT NULL
AND TICKETING_AIRLINE IS NOT NULL;


INSERT INTO FLIGHTS.SILVER.ROUTE
(
ORIGIN,
DESTINATION,
COUNTRY
)
SELECT DISTINCT
TRIM(ORIGIN),
TRIM(DESTINATION),
TRIM(COUNTRY)
FROM FLIGHTS.BRONZE.TRAVEL_RAW
WHERE TRANSACTION_KEY IS NOT NULL;


INSERT INTO FLIGHTS.SILVER.FACT_TRAVEL
SELECT
UUID_STRING(),
TRANSACTION_KEY,
NULL,
NULL,
TRIM(CABIN),
TRIM(AGENCY),
TRY_TO_DATE(DEPARTURE_DATE),
TRY_TO_DATE(ISSUE_DATE),
FLIGHT_NUMBER,
SEG_NUMBER
FROM FLIGHTS.BRONZE.TRAVEL_RAW
WHERE TRANSACTION_KEY IS NOT NULL;
