version: '3'

services:
  airflow:
    image: apache/airflow:2.8.1
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ..:/opt/project
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command: standalone