CREATE OR REPLACE TABLE bronze.stage_travel (
TRANSACTION_KEY VARCHAR,
ORIGIN VARCHAR,
DESTINATION VARCHAR,
TICKETING_AIRLINE VARCHAR,
MARKETING_AIRLINE VARCHAR,
AGENCY VARCHAR,
CABIN VARCHAR,
COUNTRY VARCHAR,
ISSUE_DATE VARCHAR,
DEPARTURE_DATE VARCHAR,
FLIGHT_NUMBER VARCHAR,
SEG_NUMBER VARCHAR
);
