CREATE OR REPLACE TABLE FLIGHTS.BRONZE.TRAVEL_RAW (

TRANSACTION_KEY VARCHAR,
ORIGIN VARCHAR,
DESTINATION VARCHAR,
TICKETING_AIRLINE VARCHAR,
MARKETING_AIRLINE VARCHAR,
AGENCY VARCHAR,
CABIN VARCHAR,
COUNTRY VARCHAR,
ISSUE_DATE VARCHAR,
DEPARTURE_DATE VARCHAR,
FLIGHT_NUMBER VARCHAR,
SEG_NUMBER VARCHAR,

_LOAD_TIMESTAMP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
_BATCH_ID VARCHAR DEFAULT UUID_STRING()

);